### ISSUE TITLE
Sensores

### ISSUE THREAD

**Issue by jorgeMorales98** [odraelk/Tarea3#2]
Agregar una breve descripción de los sensores inductivos

25d07311b3cdc8d0bb2a55e099a0b75f4c8ae64f

![sensores-sens001](https://user-images.githubusercontent.com/42308612/44310992-6426dd00-a3a5-11e8-9389-3bce274d78b4.jpg)

**Comment by odraelk** [comment]
Los sensores de proximidad inductivos sólo pueden detectar objetos metálicos. No detectan objetos no metálicos, tales como plástico, madera, papel y cerámica. A diferencia de los sensores fotoeléctricos, esto permite que un sensor de proximidad inductivos pueda detectar un objeto de metal a través de plástico opaco
